name: Michael Pollmeier ~ dev blog
author: Michael Pollmeier
description: Scala, Gremlin-Scala and other development related things
url: http://www.michaelpollmeier.com
safe: false
lsi: false
highlighter: 'rouge'
markdown: kramdown
exclude: ['Gemfile', 'Gemfile.lock']
permalink: pretty
